# Generated by Django 6.1.1 on 2026-09-12 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestamoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('plazo_meses', models.PositiveSmallIntegerField(choices=[(6, '6 meses'), (12, '12 meses'), (18, '18 meses'), (24, '24 meses')])),
                ('destino', models.CharField(choices=[('vivienda', 'Vivienda'), ('salud', 'Salud'), ('educacion', 'Educación'), ('consumo', 'Consumo'), ('otro', 'Otro')], max_length=20)),
                ('detalle', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('evaluacion', 'En evaluación'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ValeSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.PositiveIntegerField(choices=[(500000, 'Gs. 500.000'), (1000000, 'Gs. 1.000.000')])),
                ('motivo', models.CharField(choices=[('personal', 'Gastos personales'), ('salud', 'Salud'), ('educacion', 'Educación'), ('otro', 'Otro')], max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
